# Generated by Django 4.0.4 on 2022-04-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_version', models.PositiveIntegerField(blank=True, null=True)),
                ('edge_id', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('sourceHandle', models.CharField(max_length=100)),
                ('targetHandle', models.CharField(max_length=100)),
                ('animated', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_version', models.PositiveIntegerField(blank=True, null=True)),
                ('node_id', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, null=True)),
                ('caption', models.CharField(max_length=40, null=True, verbose_name='Caption')),
                ('position_x', models.FloatField(default=0, editable=False)),
                ('position_y', models.FloatField(default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
