# Generated by Django 3.2.13 on 2022-06-01 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_version', models.PositiveIntegerField(blank=True, null=True)),
                ('edge_id', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('sourceHandle', models.CharField(blank=True, max_length=100, null=True)),
                ('targetHandle', models.CharField(blank=True, max_length=100, null=True)),
                ('animated', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_version', models.PositiveIntegerField(blank=True, null=True)),
                ('node_id', models.CharField(max_length=100)),
                ('data', models.JSONField(blank=True, null=True)),
                ('caption', models.CharField(max_length=40, null=True, verbose_name='Caption')),
                ('position_x', models.FloatField(default=0, editable=False)),
                ('position_y', models.FloatField(default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('message', models.TextField()),
                ('leads_email', models.TextField()),
                ('periodic_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='django_celery_beat.periodictask')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workspace')),
            ],
        ),
    ]
