# Generated by Django 4.0.4 on 2022-04-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='sourceHandle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='edge',
            name='targetHandle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
