# Generated by Django 4.0.5 on 2022-07-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_task_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.CharField(default='customNode', max_length=100),
            preserve_default=False,
        ),
    ]
