# Generated by Django 4.0.5 on 2022-07-07 11:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to='bots/imgs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.bot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.bot'),
            preserve_default=False,
        ),
    ]
