# Generated by Django 3.2.13 on 2022-06-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
    ]
