# Generated by Django 4.0.5 on 2022-06-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(default='test subject', max_length=1000),
            preserve_default=False,
        ),
    ]
