export const sidebarMenus = {
	dashboard: {
		id: 'dashboard',
		text: 'Dashboard',
		path: '/',
		icon: 'Dashboard',
		subMenu: {
			dashboardAccounting: {
				id: 'dashboardAccounting',
				text: 'Accounting',
				path: '/accounting',
				icon: 'ViewArray',
				subMenu: {
					overView: {
						id: 'emplyeeSetup',
						text: 'Emplyee Setup',
						path: '/accounting',
						icon: 'ViewArray',
					},
					dashboardAccountingReports: {
						id: 'dashboardAccountingReports',
						text: 'Reports',
						path: '/accounting/reports',
						icon: 'ViewDay',
						subMenu: {
							dashboardAccountingReportsExpenseSummary: {
								id: 'expenseSummary',
								text: 'Expense Summary',
								path: '',
								icon: 'ViewArray',
							},
							incomeVsExpense: {
								id: 'incomeVsExpense',
								text: 'Income Vs Expense',
								path: '',
								iExpensecon: 'ViewDay',
								icon: 'ViewArray',
							},
							accountStatement: {
								id: 'accountStatement',
								text: 'Account Statement',
								path: '',
								icon: 'ViewArray',
							},
							invoiceSummary: {
								id: 'invoiceSummary',
								text: 'Invoice Summary',
								path: '',
								icon: 'ViewDay',
							},
							billSummary: {
								id: 'billSummary',
								text: 'Bill Summary',
								path: '',
								icon: 'ViewArray',
							},
							productStock: {
								id: 'productStock',
								text: 'Product Stock',
								path: '',
								icon: 'ViewDay',
							},
							profitAndLoss: {
								id: 'profitAndLoss',
								text: 'Profit And Loss',
								path: '',
								iLosscon: 'ViewArray',
							},
							transaction: {
								id: 'transaction',
								text: 'Transaction',
								path: '',
								icon: 'ViewDay',
							},
							incomeSummary: {
								id: 'incomeSummary',
								text: 'incomeSummary',
								path: '',
								icon: 'ViewArray',
							},
							taxSummary: {
								id: 'taxSummary',
								text: 'taxSummary',
								path: '',
								icon: 'ViewDay',
							},
						},
					},
				},
			},
			dashboardHrm: {
				id: 'dashboardHrm',
				text: 'HRM',
				path: '/hrm',
				icon: 'ViewDay',
			},
			dashboardProject: {
				id: 'dashboardProject',
				text: 'Project',
				path: '/',
				icon: 'ViewDay',
				subMenu: null,
			},
		},
	},
	hrmSystem: {
		id: 'hrmSystem',
		text: 'HRM System',
		path: 'hrm-system/',
		icon: 'Person',
		subMenu: {
			EmplyeeSetup: {
				id: 'emplyeeSetup',
				text: 'Emplyee Setup',
				path: 'hrm-system/emplyee-setup',
				icon: 'ViewArray',
			},
			payrollSetup: {
				id: 'hrmSystemPayrollSetup',
				text: 'Payroll Setup',
				path: 'hrm-system/payroll-setup',
				icon: 'ViewDay',
				subMenu: {
					setSalary: {
						id: 'hrmSystemPayrollSetupSetSalary',
						text: 'Set Salary',
						path: 'hrm-system/payroll-setup/set-salary',
						icon: 'ViewArray',
					},
					paySlip: {
						id: 'hrmSystemPayrollSetupPaySlip',
						text: 'Payslip',
						path: 'hrm-system/payroll-setup/payslip',
						icon: 'ViewDay',
					},
				},
			},
			leaveManagementSetup: {
				id: 'hrmSystemLeaveManagementSetup',
				text: 'Leave Management Setup',
				path: 'hrm-system/leave-management-setup',
				icon: 'ViewDay',
				subMenu: {
					manageLeave: {
						id: 'hrmSystemLeaveManagementSetupManageLeave',
						text: 'Manage Leave',
						path: 'hrm-system/leave-management-setup/manage-leave',
						icon: 'ViewArray',
					},
					attendance: {
						id: 'hrmSystemLeaveManagementSetupAttendance',
						text: 'Attendance',
						path: 'hrm-system/leave-management-setup/attendance',
						icon: 'ViewDay',
						subMenu: {
							markAttendance: {
								id: 'hrmSystemLeaveManagementSetupAttendanceMarkAttendance',
								text: 'Mark Attendance',
								path: 'hrm-system/leave-management-setup/mark-attendance',
								icon: 'ViewArray',
							},
							bulkAttendance: {
								id: 'hrmSystemLeaveManagementSetupAttendanceBulkAttendance',
								text: 'Bulk Attendance',
								path: 'hrm-system/leave-management-setup/bulk-attendance',
								icon: 'ViewDay',
							},
						},
					},
				},
			},
			performanceSetup: {
				id: 'hrmSystemPerformanceSetup',
				text: 'Performance Setup',
				path: 'hrm-system/performance-setup/',
				icon: 'ViewDay',
				subMenu: {
					indicator: {
						id: 'performanceSetupIndicator',
						text: 'Indicator',
						path: 'hrm-system/performance-setup/indicator',
						icon: 'ViewArray',
					},
					appraisal: {
						id: 'performanceSetupAppraisal',
						text: 'Appraisal',
						path: 'hrm-system/performance-setup/appraisal',
						icon: 'ViewDay',
					},
					goalTracking: {
						id: 'performanceSetupGoalTracking',
						text: 'Goal Tracking',
						path: 'hrm-system/performance-setup/goal-tracking',
						icon: 'ViewDay',
					},
				},
			},
			trainingSetup: {
				id: 'hrmSystemPerformanceSetup',
				text: 'Training Setup',
				path: 'hrm-system/training-setup',
				icon: 'ViewDay',
				subMenu: {
					trainingList: {
						id: 'hrmSystemPerformanceSetupTrainingList',
						text: 'Training List',
						path: 'hrm-system/training-setup/training-list',
						icon: 'ViewArray',
					},
					trainer: {
						id: 'hrmSystemPerformanceSetupTrainer',
						text: 'Trainer',
						path: 'hrm-system/training-setup/trainer',
						icon: 'ViewDay',
					},
				},
			},
			recruitmentSetup: {
				id: 'hrmSystemRecruitmentSetup',
				text: 'Leave Management Setup',
				path: '/leave-management-setup',
				icon: 'ViewDay',
				subMenu: {
					jobs: {
						id: 'hrmSystemRecruitmentSetupJobs',
						text: 'Jobs',
						path: 'hrm-system/recruitment-setup/jobs',
						icon: 'ViewArray',
					},
					jobCreate: {
						id: 'hrmSystemRecruitmentSetupJobCreate',
						text: 'Job Create',
						path: 'hrm-system/recruitment-setup/job-create',
						icon: 'ViewDay',
					},
					jobApplication: {
						id: 'hrmSystemRecruitmentSetupJobApplication',
						text: 'Job Application',
						path: 'hrm-system/recruitment-setup/job-application',
						icon: 'ViewDay',
					},
					jobCandidate: {
						id: 'hrmSystemRecruitmentSetupJobCandidate',
						text: 'Job Candidate',
						path: 'hrm-system/recruitment-setup/job-cadidate',
						icon: 'ViewArray',
					},
					jobOnBoarding: {
						id: 'hrmSystemRecruitmentSetupJobOnBoarding',
						text: 'Job On-Boarding',
						path: 'hrm-system/recruitment-setup/job-on-boarding',
						icon: 'ViewDay',
					},
					customQuestion: {
						id: 'hrmSystemRecruitmentSetupCustomQuestion',
						text: 'Custom Question',
						path: 'hrm-system/recruitment-setup/custom-question',
						icon: 'ViewDay',
					},
					interviewSchedule: {
						id: 'hrmSystemRecruitmentSetupInterviewSchedule',
						text: 'Interview Schedule',
						path: 'hrm-system/recruitment-setup/interview-schedule',
						icon: 'ViewArray',
					},
					career: {
						id: 'hrmSystemRecruitmentSetupCareer',
						text: 'Career',
						path: 'hrm-system/recruitment-setup/career',
						icon: 'ViewDay',
					},
				},
			},
			hrmSystemHrAdminSetup: {
				id: 'performance-setup',
				text: 'Leave Management Setup',
				path: 'hrm-system/hr-admin-setup',
				icon: 'ViewDay',
				subMenu: {
					award: {
						id: 'award',
						text: 'Award',
						path: 'hrm-system/hr-admin-setup/award',
						icon: 'ViewArray',
					},
					transfer: {
						id: 'transfer',
						text: 'Transfer',
						path: 'hrm-system/hr-admin-setup/transfer',
						icon: 'ViewDay',
					},
					resignation: {
						id: 'resignation',
						text: 'Resignation',
						path: 'hrm-system/hr-admin-setup/resignation',
						icon: 'ViewDay',
					},
					trip: {
						id: 'trip',
						text: 'Trip Setup',
						path: 'hrm-system/hr-admin-setup/trip',
						icon: 'ViewArray',
					},
					promotion: {
						id: 'promotion',
						text: 'Promotion',
						path: 'hrm-system/hr-admin-setup/promotion',
						icon: 'ViewDay',
					},
					complaints: {
						id: 'complaints',
						text: 'Complaints',
						path: 'hrm-system/hr-admin-setup/complaints',
						icon: 'ViewDay',
					},
					warning: {
						id: 'warning',
						text: 'Warning Setup',
						path: 'hrm-system/hr-admin-setup/warning',
						icon: 'ViewArray',
					},
					termination: {
						id: 'termination',
						text: 'Termination',
						path: 'hrm-system/hr-admin-setup/termination',
						icon: 'ViewDay',
					},
					announcement: {
						id: 'announcement',
						text: 'Announcement Setup',
						path: 'hrm-system/hr-admin-setup/announcement',
						icon: 'ViewArray',
					},
					holidays: {
						id: 'holidays',
						text: 'Holidays',
						path: 'hrm-system/hr-admin-setup/holidays',
						icon: 'ViewDay',
					},
				},
			},
			eventSetup: {
				id: 'eventSetup',
				text: 'Event Setup',
				path: 'hrm-system/event-setup',
				icon: 'ViewDay',
			},
			meeting: {
				id: 'meeting',
				text: 'Meeting',
				path: 'hrm-system/meeting',
				icon: 'ViewDay',
			},
			employeesAssetSetup: {
				id: 'employeesAssetSetup',
				text: 'Employees Asset Setup',
				path: 'hrm-system/employees-asset-setup',
				icon: 'ViewDay',
			},
			documentSetup: {
				id: 'documentSetup',
				text: 'Document Setup',
				path: 'hrm-system/document-setup',
				icon: 'ViewDay',
			},
			companyPolicy: {
				id: 'companyPolicy',
				text: 'Company Policy',
				path: 'hrm-system/company-policy',
				icon: 'ViewDay',
			},
			hrmSystemSetup: {
				id: 'hrmSystemSetup',
				text: 'Hrm System Setup',
				path: 'hrm-system/hrm-system-setup',
				icon: 'ViewDay',
			},
		},
	},
	accountingSystem: {
		id: 'accountingSystem',
		text: 'Accounting System',
		path: 'accounting-system',
		icon: 'Box',
		subMenu: {
			customer: {
				id: 'customer',
				text: 'Customer',
				path: 'accounting-system/customer',
				icon: 'ViewArray',
			},
			vendor: {
				id: 'vendor',
				text: 'Vendor',
				path: 'accounting-system/vendor',
				icon: 'ViewDay',
			},
			proposal: {
				id: 'proposal',
				text: 'Proposal',
				path: 'accounting-system/proposal',
				icon: 'ViewDay',
			},
			banking: {
				id: 'banking',
				text: 'Banking',
				path: 'accounting-system/banking',
				icon: 'ViewArray',
				subMenu: {
					customer: {
						id: 'customer',
						text: 'Customer',
						path: 'accounting-system/customer',
						icon: 'ViewArray',
					},
				},
			},
			income: {
				id: 'income',
				text: 'Income',
				path: 'accounting-system/income',
				icon: 'ViewDay',
				subMenu: {
					customer: {
						id: 'customer',
						text: 'Customer',
						path: 'accounting-system/customer',
						icon: 'ViewArray',
					},
				},
			},
			expense: {
				id: 'expense',
				text: 'Expense',
				path: 'accounting-system/expense',
				icon: 'ViewDay',
				subMenu: {
					customer: {
						id: 'customer',
						text: 'Customer',
						path: 'accounting-system/customer',
						icon: 'ViewArray',
					},
				},
			},
			doubleEntry: {
				id: 'doubleEntry',
				text: 'Double Entry',
				path: 'accounting-system/doubleEntry',
				icon: 'ViewDay',
				subMenu: {
					customer: {
						id: 'customer',
						text: 'Customer',
						path: 'accounting-system/customer',
						icon: 'ViewArray',
					},
				},
			},
			budgetPlanner: {
				id: 'budgetPlanner',
				text: 'Budget Planner',
				path: 'accounting-system/budgetPlanner',
				icon: 'ViewDay',
			},
			financialGoal: {
				id: 'financialGoal',
				text: 'Financial Goal',
				path: 'accounting-system/financialGoal',
				icon: 'ViewDay',
			},
			accountingSetup: {
				id: 'accountingSetup',
				text: 'Accounting Setup',
				path: 'accounting-system/accountingSetup',
				icon: 'ViewDay',
			},
			printSettings: {
				id: 'printSettings',
				text: 'Print Settings',
				path: 'accounting-system/printSettings',
				icon: 'ViewDay',
			},
		},
	},
	crmSystem: {
		id: 'CRMSystem',
		text: 'CRM',
		path: 'crm-system',
		icon: 'ContentCopy',
		subMenu: {
			leads: {
				id: 'leads',
				text: 'Leads',
				path: 'crm-system/leads',
				icon: 'ViewArray',
			},
			deals: {
				id: 'deals',
				text: 'Deals',
				path: 'crm-system/deals',
				icon: 'ViewDay',
			},
			formBuilder: {
				id: 'formBuilder',
				text: 'Form Builder',
				path: 'crm-system/for-builder',
				icon: 'ViewDay',
			},
			contract: {
				id: 'contract',
				text: 'Contract',
				path: 'crm-system/contract',
				icon: 'ViewArray',
			},
			crmSystemSetup: {
				id: 'crmSystemSetup',
				text: 'CRM System Setup',
				path: 'crm-system/crm-system-setup',
				icon: 'ViewDay',
			},
		},
	},
	projectSystem: {
		id: 'projectSystem',
		text: 'Project System',
		path: 'project-system',
		icon: 'Share',
		subMenu: {
			projects: {
				id: 'projects',
				text: 'Projects',
				path: 'project-system/projects',
				icon: 'ViewArray',
			},
			tasks: {
				id: 'tasks',
				text: 'Tasks',
				path: 'project-system/tasks',
				icon: 'ViewDay',
			},
			timesheet: {
				id: 'timesheet',
				text: 'Timesheet',
				path: 'project-system/timesheet',
				icon: 'ViewDay',
			},
			bug: {
				id: 'bug',
				text: 'Bug',
				path: 'project-system/bug',
				icon: 'ViewArray',
			},
			tracker: {
				id: 'tracker',
				text: 'Tracker',
				path: 'project-system/tracker',
				icon: 'ViewArray',
			},
			projectSystemSetup: {
				id: 'projectSystemSetup',
				text: 'Project System Setup',
				path: 'project-system/project-system-setup',
				icon: 'ViewDay',
			},
		},
	},
	userManagement: {
		id: 'user-management',
		text: 'User Managements',
		path: 'user-management',
		icon: 'People',
		subMenu: {
			user: {
				id: 'user-management-user',
				text: 'User',
				path: 'user-management/user',
				icon: 'ViewArray',
			},
			role: {
				id: 'user-management-role',
				text: 'Role',
				path: 'user-management/role',
				icon: 'ViewDay',
			},
			client: {
				id: 'user-management-client',
				text: 'Client',
				path: 'user-management/client',
				icon: 'ViewDay',
			},
		},
	},
	productsSystem: {
		id: 'productsSystem',
		text: 'Products System',
		path: 'products-system',
		icon: 'Cart2',
		subMenu: {
			role: {
				id: 'user-management-role',
				text: 'Role',
				path: 'products-system/role',
				icon: 'ViewDay',
			},
			client: {
				id: 'products-system-client',
				text: 'Client',
				path: 'products-system/client',
				icon: 'ViewDay',
			},
		},
	},
	supportSystem: {
		id: 'support-system',
		text: 'Support System',
		path: 'support-system',
		icon: 'Headphones',
		subMenu: null,
	},
	zoomMeeting: {
		id: 'zoomMeeting',
		text: 'Zoom Meeting',
		path: 'summary',
		icon: 'CameraVideoFill',
		subMenu: null,
	},
	messenger: {
		id: 'messenger',
		text: 'Messenger',
		path: 'messenger',
		icon: 'Messenger',
		subMenu: null,
	},
	systemSetup: {
		id: 'system-setup',
		text: 'System Setup',
		path: 'system-setup',
		icon: 'Gear',
		subMenu: {
			systemSettings: {
				id: 'system-settings',
				text: 'System Settings',
				path: 'system-setup/system-settings',
				icon: 'ViewDay',
			},
			setupSubscriptionPlans: {
				id: 'setup-subscription-plans',
				text: 'Setup Subscription Plans',
				path: 'system-setup/setup-subscription-plans',
				icon: 'ViewDay',
			},
			order: {
				id: 'order',
				text: 'Order',
				path: 'system-setup/order',
				icon: 'ViewDay',
			},
		},
	},
};

export const componentsMenu = {
	bootstrap: {
		id: 'bootstrap',
		text: 'Bootstrap',
		icon: 'Extension',
	},
	notification: {
		id: 'notification',
		text: 'Notification',
		path: 'notifications',
		icon: 'NotificationsNone',
	},
	hooks: {
		id: 'hooks',
		text: 'Hooks',
		path: 'hooks',
		icon: 'Anchor',
	},
};

export const productsMenu = {
	companyA: {
		id: 'companyA',
		text: 'Company A',
		path: 'grid-pages/products',
		subMenu: null,
	},
	companyB: { id: 'companyB', text: 'Company B', path: '/', subMenu: null },
	companyC: { id: 'companyC', text: 'Company C', path: '/', subMenu: null },
	companyD: { id: 'companyD', text: 'Company D', path: '/', subMenu: null },
};
